<a href="https://colab.research.google.com/github/csrajath/Practicing-DataScience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Arrays are like lists in python except for the fact that they can hold similar type elements only
*  Array elements can be accesed like lists for slicing, indexing and etc.
* The first element in np.shape is the column and the second is the row.

### To practice
* Define an array
* Define a multi dimensional array
* Perform slicing Operation on both, check the shape and object types.
* Define an array of integer elements and later convert it to float
* Use matplotlib to read an image and crop it using Numpy
* Convert a list to an array and an array to a list
* Perform reshape operation on a multi-dimensional array

In [94]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline 

In [96]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [104]:
b = np.array([['a','b'],[5,6]])
b

array([['a', 'b'],
       ['5', '6']], dtype='<U1')

In [105]:
b.shape

(2, 2)

In [106]:
b.dtype

dtype('<U1')

In [108]:
b[:,1]

array(['b', '6'], dtype='<U1')

In [130]:
x = np.array(range(20))
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [136]:
x.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [137]:
x.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]